[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "FeralCompany"
name = "FeralCommon"
description = "A collection of common utilities and classes that are used across various FeralCompany projects"
websiteUrl = "https://github.com/FeralCompany/FeralCommon"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "../README.md"
changelog = "../CHANGELOG.md"
license = "../../LICENSE"

[[build.copy]]
source = "../bin/netstandard2.1/FeralCommon.dll"
target = "BepInEx/plugins/FeralCommon.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "../README.md"
target = "README.md"

[[build.copy]]
source = "../LICENSE"
target = "LICENSE"

[publish]
communities = [ "lethal-company" ]

[publish.categories]
lethal-company = [ "bepinex", "libraries", "tools" ]
