name: Release tagged build

on:
  push:
    tags: [ '*' ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      USE_STUBBED_LIBS: 1
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Delete old release if it already exists
        run: gh release delete --yes "${RELEASE_VERSION}"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Release under current tag
        run: |
          export "CHANGELOG_FILE=$(mktemp --suffix=.md)"
          echo "CHANGELOG_FILE=${CHANGELOG_FILE}" >> $GITHUB_ENV
          gh api --method POST -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/releases/generate-notes" \
            -f tag_name="${RELEASE_VERSION}" \
            --jq ".body" > "${CHANGELOG_FILE}"
          cat "${CHANGELOG_FILE}"
          gh release create "${RELEASE_VERSION}" -F "${CHANGELOG_FILE}"
        shell: bash
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
